version: '3.7'

volumes:
  hadoop_namenode:
  hadoop_datanode:
  prometheus_data:
  grafana_data:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
  controller_data:
  broker_data:
  server_data:
  minion_data:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: unless-stopped
    ports:
      - 9870:9870
      - 9800:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2G"
        reservations:
          cpus: "0.5"
          memory: "1G"      
    networks:
      vpcbr:          

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: unless-stopped
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2G"
        reservations:
          cpus: "0.5"
          memory: "1G"      
    networks:
      vpcbr:          

  zookeeper:
    image: zookeeper:3.5.6
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"
    networks:
      vpcbr:          

  kafka:
    image: confluentinc/cp-kafka:4.1.4
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TOPIC_AUTO_CREATE: 1
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    networks:
      vpcbr:          

  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: kafka:29092
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"
    networks:
      vpcbr:          

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      VERSION_CONFIG: 2
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"
    networks:
      vpcbr:          

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"
    networks:
      vpcbr:          

  pinot-controller:
    image: apachepinot/pinot:0.10.0
    command: "StartController -zkAddress zookeeper:2181 -configFileName /config/pinot-controller.conf"
    container_name: "pinot-controller"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9010:9010"
    volumes:
      - ./config:/config
      - controller_data:/tmp/data
    environment:
      CONFIG_VERSION: "7"
      JAVA_OPTS: "-javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=9010:/opt/pinot/etc/jmx_prometheus_javaagent/configs/pinot.yml -Dplugins.dir=/opt/pinot/plugins -Dplugins.include=pinot-hdfs -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
      CLASSPATH_PREFIX: "/config/hadoop/hadoop-hdfs-2.7.1.jar:/config/hadoop/hadoop-annotations-2.7.1.jar:/config/hadoop/hadoop-auth-2.7.1.jar:/config/hadoop/hadoop-common-2.7.1.jar:/config/hadoop/guava-11.0.2.jar:/config/hadoop/gson-2.2.4.jar"
    depends_on:
      - zookeeper
      - namenode
      - datanode
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "6G"
        reservations:
          cpus: "1"
          memory: "4G"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.20

  pinot-broker:
    image: apachepinot/pinot:0.10.0
    command: "StartBroker -zkAddress zookeeper:2181"
    container_name: "pinot-broker"
    restart: unless-stopped
    ports:
      - "8099:8099"
      - "9011:9011"
    volumes:
      - broker_data:/tmp/data
    environment:
      JAVA_OPTS: "-javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=9011:/opt/pinot/etc/jmx_prometheus_javaagent/configs/pinot.yml -Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-broker.log"
    depends_on:
      - pinot-controller
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.21

  pinot-server:
    image: apachepinot/pinot:0.10.0
    command: "StartServer -zkAddress zookeeper:2181 -configFileName /config/pinot-server.conf"
    container_name: "pinot-server"
    restart: unless-stopped
    ports:
      - "9012:9012"
    volumes:
      - ./config:/config
      - server_data:/tmp/data
    environment:
      VERSION_CONFIG: "4"
      JAVA_OPTS: "-javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=9012:/opt/pinot/etc/jmx_prometheus_javaagent/configs/pinot.yml -Dplugins.dir=/opt/pinot/plugins -Dplugins.include=pinot-hdfs -Xms2G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log"
      CLASSPATH_PREFIX: "/config/hadoop/hadoop-hdfs-2.7.1.jar:/config/hadoop/hadoop-annotations-2.7.1.jar:/config/hadoop/hadoop-auth-2.7.1.jar:/config/hadoop/hadoop-common-2.7.1.jar:/config/hadoop/guava-11.0.2.jar:/config/hadoop/gson-2.2.4.jar"
    depends_on:
      - pinot-broker
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "8G"
        reservations:
          cpus: "2"
          memory: "6G"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.22

  pinot-minion:
    image: apachepinot/pinot:0.10.0
    command: "StartMinion -zkAddress zookeeper:2181 -configFileName /config/pinot-minion.conf"
    container_name: "pinot-minion"
    restart: unless-stopped
    ports:
      - "9013:9013"
    volumes:
      - ./config:/config
      - minion_data:/tmp/data
    environment:
      VERSION_CONFIG: "4"
      JAVA_OPTS: "-javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=9013:/opt/pinot/etc/jmx_prometheus_javaagent/configs/pinot.yml -Dplugins.dir=/opt/pinot/plugins -Xms2G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log"
      CLASSPATH_PREFIX: "/config/hadoop/hadoop-hdfs-2.7.1.jar:/config/hadoop/hadoop-annotations-2.7.1.jar:/config/hadoop/hadoop-auth-2.7.1.jar:/config/hadoop/hadoop-common-2.7.1.jar:/config/hadoop/guava-11.0.2.jar:/config/hadoop/gson-2.2.4.jar"      
    depends_on:
      - pinot-server
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
        reservations:
          cpus: "1"
          memory: "3G"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.23
