{
 "title": "App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,3m,5m,15m,30m,1h,5h,7h,15h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Write total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table)(increase(pinot_server_realtimeRowsConsumed_Count{}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Write rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (table)  (avg by (table) (rate(pinot_server_realtimeRowsConsumed_Count[5m])))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Query total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table)(increase(finch_request_stop_duration_count{}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(table)(rate(finch_request_stop_duration_count{}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(finch_request_stop_duration_sum{}[$interval])) / sum by (status) (rate(finch_request_stop_duration_count{}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query median",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(finch_request_stop_duration_bucket{}[$interval]))by(status,le))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Query 99p",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(finch_request_stop_duration_bucket{}[$interval]))by(status,le))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Queue avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(finch_queue_stop_duration_sum{}[$interval])) / sum by (status) (rate(finch_queue_stop_duration_count{}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Queue median",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(finch_queue_stop_duration_bucket{}[$interval]))by(status,le))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Queue 99p",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(finch_queue_stop_duration_bucket{}[$interval]))by(status,le))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max idle time exceeded",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(finch_conn_max_idle_time_exceeded_idle_time{}[$interval]))"
    }
   ]
  }
 ]
}